### ISSUE TITLE
What is the difference with the wet-boew/gcweb-jekyll variant?

### ISSUE THREAD

**Issue by duboisp** [canada-ca/canada-ca-jekyll-boilerplate#1]
@delisma what is this repository for?

Why do you need an independent clone of  https://github.com/wet-boew/gcweb-jekyll ?

**Comment by nschonni** [comment]
My guess would be for a Jekyll variant of https://github.com/canada-ca/template-gabarit, but that is only a guess :)

**Comment by delisma** [comment]
@duboisp This is not a clone but a boilerplate to call the gcweb-jekyll theme. As @nschonni is saying this is a template for departments to fork with most Jekyll settings and folder structure setup. Still in its early stage but eventually even tutorials and other documentation related to building a static web site for the government could live here.

**Comment by gcharest** [comment]
I know this issue is closed but if this is intended as a template, I would suggest identifying it as such. See repo settings, right under repository name --> **Template repository**

**Comment by delisma** [comment]
@gcharest Thanks for the tip. I wasn't aware of that feature.
