### ISSUE TITLE
Mark as template repository once ready

### ISSUE THREAD

**Issue by nschonni** [canada-ca/canada-ca-jekyll-boilerplate#2]
> I know this issue is closed but if this is intended as a template, I would suggest identifying it as such. See repo settings, right under repository name --> **Template repository**

_Originally posted by @gcharest in https://github.com/canada-ca/canada-ca-jekyll-boilerplate/issues/1#issuecomment-573356309_

**Comment by jvanulde** [comment]
What is the difference between this and wet-boew/gcweb-jekyll? Both look like templates to me.

**Comment by delisma** [comment]
> What is the difference between this and wet-boew/gcweb-jekyll? Both look like templates to me.

This repo can be forked as-is and will call the template from `wet-boew/gcweb-jekyll`. It's not full fledge yet but it is meant to be a reference implementation of remotely calling the theme from the gcweb-jekyll repo.
